### ISSUE TITLE
Scripts running for too long

### ISSUE THREAD

**Issue by gayatripanda5** [durrantlab/wisp#1]
Dear Developers, 
I want to determine the allosteric pathway connecting two residues in two separate domains of my system. 
I had setup a trial job using the files attached, and I ran this jib using 16 processors. The script was running for 3 weeks and then I had to kill it as I couldn't understand why is it taking so long. Kindly help me understand what could be the possible reason behind it and as I want to run it for multiple proteins. Kindly suggest a way to increase the efficiency of the script. 

The files used 
[files_wisp.tar.gz](https://github.com/durrantlab/wisp/files/12861282/files_wisp.tar.gz)

**Comment by aalexmmaldonado** [comment]
Thank you for bringing this to our attention! We will look into this, but it may take some time.

**Comment by gayatripanda5** [comment]
Thanks a lot for your response. I'm really looking forward to its resolution since my work is stuck at this step only. Thanks

**Comment by gayatripanda5** [comment]
Dear Developers, 
Could you please help me in resolving this issue?

**Comment by aalexmmaldonado** [comment]
Hey @gayatripanda5, I am currently reworking the organization of the code. You can track my progress here: #2. I will start troubleshooting your example once I ensure our original test passes with the new format.

I am hoping to have this resolved in a week or two.

**Comment by gayatripanda5** [comment]
Thanks for helping me out. I will follow the attached link.

**Comment by Saleh-OM4R** [comment]
Hi @aalexmmaldonado ,
I'm trying the wisp.py code and it is taking a long time to run; it gets stuck exactly at the path calculation step. I tried to increase the number of processors, but still it did not help. Was the issue mentioned above fixed or are there still known issues with the code?   
Thanks for the tool, Cheers,

**Comment by aalexmmaldonado** [comment]
Accidentally closed this.

**Comment by aalexmmaldonado** [comment]
Hey @gayatripanda5, I have been able to look at this again and discovered a few things.

1. Your PDB has multiple chains but no chain IDs. WISP would automatically assign everything as chain A, which was corrected in #3.
2. WISP ran for so long because of a combinatorial explosion in your system. WISP did not have a check or warn the user of this. We implemented an estimation of the number of paths, and if it is above some threshold, we terminate the calculation. You can bump this up manually, but it will run for as long as it did.

I will leave this open for now while I look into it more.
